### ISSUE TITLE
[question] Possibly incorrect formula for pmax?

### ISSUE THREAD

**Issue by paulromano** [lcpp-org/RustBCA#179]
First off, thanks for your development of this wonderful open source package. I'm trying to learn the details of BCA code implementations and RustBCA has been really valuable for that purpose. When comparing the implementation to textbooks/papers, I ran across this line:
https://github.com/lcpp-org/RustBCA/blob/82145d911177454fc4ccdbac661b5bee3053b9ac/src/bca.rs#L271

Shouldn't it be `pmax = mfp/SQRTPI`? If I compare to Eq. 7.1.15 in Eckstein 1991 or Eq. 7-27 in the SRIM textbook, it looks like it should be `SQRTPI` instead of `SQRT2PI`.

**Comment by drobnyjt** [comment]
I believe you are correct! Thankfully it looks like this bug is limited to the high energy free flight path model, so most applications will not be affected, but it could have an effect on high energy simulations; [Line 326](https://github.com/lcpp-org/RustBCA/blob/82145d911177454fc4ccdbac661b5bee3053b9ac/src/bca.rs#L326), for the low-energy case, has the correct formula. I'll push a fix now.

**Comment by drobnyjt** [comment]
Here's the results of before and after the fix - note that I accidentally switched the colors of the two cases. It looks like the effect is small, at least at 1 keV, but it's still better to be correct than not!

![before_fix](https://user-images.githubusercontent.com/37962344/155013748-42a32950-8ec2-4f1e-a25c-a03811ea3407.png)
![after_fix](https://user-images.githubusercontent.com/37962344/155013750-a5ae1e13-3bd5-4b5c-a033-ac9d9a45191d.png)

**Comment by paulromano** [comment]
Thanks for following up with that @drobnyjt! Good to know it's not a major impact
