### ISSUE TITLE
[question] Layered targets in python bindings

### ISSUE THREAD

**Issue by crivaronicolini** [lcpp-org/RustBCA#199]
Hi! I was wondering how can I set up a layered target from the python side.
I've looked at the example input for the layered target, but it's difficult to see how to set it up in python.
Thanks!

**Comment by drobnyjt** [comment]
Hi @crivaronicolini! Quick clarifying question: are you referring to the Python bindings (compound_bca_list_py, simple_bca_list_py, simple_bca_py) or to the Python scripts for generating input files for use with the standalone code?

**Comment by crivaronicolini** [comment]
Hi! Thanks for the quick answer. Yes I mean the python bindings, in particular, the examples/test_rustbca.py file.
Which one of the ways you mention is the recommended way of running the program?

**Comment by drobnyjt** [comment]
Gotcha - so right now, all of the bindings only implement the "0D" composition model, so there's no way to set up a layered target at present. The bindings are really intended for code-coupling; the recommended way to use the code for all other use cases is the standalone version, where .toml input files (e.g., RustBCA/examples/layered_geometry_1D.toml) are given to the executable. The Python bindings are noticeably slower than running the standalone code, mostly (but not entirely) because you lose multithreading.

I don't think it would be terribly difficult to add that feature, it just hasn't come up yet. The bindings in general could use an ergonomics pass, but I've been reluctant to since it would break compatibility... I'll open an issue later this morning to add a layered target version of the python bindings, and hopefully it will also be easier to use than the existing versions.

**Comment by drobnyjt** [comment]
[Issue opened](https://github.com/lcpp-org/RustBCA/issues/200). I don't have an exact timeline for it, but I'll try to find the time to work on this issue in the next 1-2 weeks.

**Comment by drobnyjt** [comment]
Hi @crivaronicolini, I've added a new function to the Python bindings that includes a layered, 1D target.

In test_rustbca.py, starting from [this line](https://github.com/lcpp-org/RustBCA/blob/38bca1f76d1573ab1b2fa7c6e6f13ef2d2d221a2/examples/test_rustbca.py#L97), is an example of its usage. I've done some light testing of it, but haven't put it all the way through its paces - let me know if this feature works for you and if you run into any issues.

**Comment by drobnyjt** [comment]
Going to close this for now; @crivaronicolini, please feel free to comment here if you have any further questions on this topic!
