### ISSUE TITLE
[bug?]  Trimesh cannot detect particles inside the object?

### ISSUE THREAD

**Issue by Sir-Goshawk** [lcpp-org/RustBCA#234]
**Description**
I was running comparisons for simulations of trimesh of a sphere and a `SPHERE` simulation of the same dimensions when I noticed different results, mostly the number of particles that were left inside the object.
Running different trimesh objects, including the same sphere with varying numbers of triangles, size, and a tetrahedron for comparison made me suspect it might not be able to accurately detect particles inside the trimesh, resulting in less collisions.
I cannot tell if it's a limitation with running a trimesh simulation or an actual bug.

**To Reproduce**
I have attached four toml files (in txt due to hosting), `sphere.txt`, `denseTri.txt`, `sparseTri.txt`, and `tet.txt`. 
All of these are modified from the `tungsten_twist_trimesh.toml` file in the examples folder. 
[tet.txt](https://github.com/lcpp-org/RustBCA/files/14035275/tet.txt)
[sparseTri.txt](https://github.com/lcpp-org/RustBCA/files/14035277/sparseTri.txt)
[denseTri.txt](https://github.com/lcpp-org/RustBCA/files/14035278/denseTri.txt)
[sphere.txt](https://github.com/lcpp-org/RustBCA/files/14035279/sphere.txt)

All particles started at around the center of the object. And, at least according to my runs, trimesh simulations have particles being detected as not inside when they are. (still close to the center/within the boundary)

**Expected behavior**
I'm not sure, should a dense trimesh sphere match the simulation with a `SPHERE` with the same radius?
Here are the outputs for running `sphere.txt` and `denseTri.txt`
[spheredeposited.txt](https://github.com/lcpp-org/RustBCA/files/14035317/spheredeposited.txt)
[trimesh spheredeposited.txt](https://github.com/lcpp-org/RustBCA/files/14035318/trimesh.spheredeposited.txt)

**Comment by Sir-Goshawk** [comment]
Accidentally posted, will open later after gathering all the information

**Comment by Sir-Goshawk** [comment]
Edited the issue, reopen.

**Comment by drobnyjt** [comment]
@Sir-Goshawk Thanks for opening this issue; I'll look into it.

In the meantime, have you tested your mesh to ensure all normals are pointed outwards and for "watertightness"?

**Comment by drobnyjt** [comment]
@Sir-Goshawk

I opened the mesh using trimesh; your mesh is watertight:
```
import trimesh
import toml

input_file = toml.load('DenseTri.txt')

vertices = input_file["geometry_input"]["vertices"]
faces = input_file["geometry_input"]["indices"]

mesh = trimesh.Trimesh(vertices=vertices, faces=faces)

print(mesh.is_watertight) #Returns True

```
However, I think half of your sphere has normals facing the wrong direction:
```
mesh.show()
```
![image](https://github.com/lcpp-org/RustBCA/assets/37962344/e4571010-14e8-4baf-9261-dd525d671d51)

If you fix the normals with trimesh:

```
mesh.fix_normals()
mesh.show()
```
![image](https://github.com/lcpp-org/RustBCA/assets/37962344/410d764c-cf5c-481a-86c4-067cc80fcd30)

If you fix the normals of your mesh I think it should fix the issue.

**Comment by Sir-Goshawk** [comment]
Yeah... that seems to be the issue. So it was my fault.

Thank you for your time, I'll close the thread.

**Comment by drobnyjt** [comment]
@Sir-Goshawk No, that would be unexpected behavior - the results should be similar. Can you share the two input files that produced those outputs?

**Comment by drobnyjt** [comment]
@Sir-Goshawk Since RustBCA will ignore extra toml options if they don't apply, you can make a single input file that will work for both SPHERE and TRIMESH, by including all three fields: `indices`, `vertices`, and `radius`. I've taken one of your input files, denseTri.txt, fixed it using trimesh, removed some extraneous options, added a radius, and ran it in both SPHERE and TRIMESH modes. That input file can be found here:

[denseTri_fixed.txt](https://github.com/lcpp-org/RustBCA/files/14056746/denseTri_fixed.txt)

When running this way, I get the following number of deposited particles in each mode:

TRIMESH: 961/1000
SPHERE: 950/1000

Which is consistent with my expectation that SPHERE and TRIMESH with a suitable mesh should produce similar results.

Scatterplot of the stopped particles:
![Figure_1](https://github.com/lcpp-org/RustBCA/assets/37962344/9dd90895-359a-4713-8f11-f7cd573277ac)

Implantation distribution in x of the stopped particles:
![Figure_12](https://github.com/lcpp-org/RustBCA/assets/37962344/5aabd1a5-e142-4048-be6b-e8d8a2118e1a)

My suspicion is that there is a subtle disagreement between your input files; try repeating with the input file provided above and let me know if you're still seeing dissimilar results.

**Comment by Sir-Goshawk** [comment]
Oh, I see, I need to fix both the indices and vertices of the trimesh. 

Thank you so much.
