### ISSUE TITLE
[question] error message significance to sputtering yield result

### ISSUE THREAD

**Issue by sonatav2** [lcpp-org/RustBCA#249]
Running a normal-incidence B on B simulation at 7.2556e+04 eV produced a non-zero sputtering  yield (similar input files as the other recent issue I submitted), but the simulation ended prematurely at 91% complete with the error message shown below. Is this likely to negatively effect the accuracy of the sputtering yield? If so, do you have recommendations for addressing it? Thank you for your time!

RustBCA(93457,0x70000faec000) malloc: Heap corruption detected, free list is damaged at 0x600001e53660
*** Incorrect guard value: 0
RustBCA(93457,0x70000faec000) malloc: *** set a breakpoint in malloc_error_break to debug
RustBCA(93457,0x700011310000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x700011d1f000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x700011d1f000) malloc: *** set a breakpoint in malloc_error_break to debug
RustBCA(93457,0x700011310000) malloc: *** set a breakpoint in malloc_error_break to debug
RustBCA(93457,0x70000f8e9000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x70000f8e9000) malloc: *** set a breakpoint in malloc_error_break to debug
RustBCA(93457,0x700012328000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard RustBCA(93457,0x700011b1c000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x7000106fe000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
value: 0
RustBCA(93457,0x700011513000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x700011919000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x7000102f8000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x70001272e000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0
RustBCA(93457,0x70000fef2000) malloc: Heap corruption detected, free list is damaged at 0x600001e43fe0
*** Incorrect guard value: 0

**Comment by drobnyjt** [comment]
Honestly, this one is a head scratcher. As far as I know, there shouldn't be any issues with malloc in the standalone code, since Rust should be memory-safe everywhere... I don't know what the source of the error message is.

Can you share the input file that generates this message? I will try to recreate it, but I am concerned it may be system-dependent. Another thing I would suggest trying is to just run the input file again and see if the error persists. 

I would manually skim the output file to see if there any incomplete rows, but otherwise I think the sputtered lists should be correct, but you might have to take into account the fact that it only ran 91% of the ions.

**Comment by sonatav2** [comment]
Thank you! No need to try recreating it.
