### ISSUE TITLE
[feature] New output file: summary of yield, reflection coefficient, etc.

### ISSUE THREAD

**Issue by drobnyjt** [lcpp-org/RustBCA#62]

**Comment by hayes2419** [comment]
For every spatial point (1-5) GITR only needs 4 things from RustBCA and hPIC. 

1. total impurity flux
2. energy distribution of sputtered impurities
3. + 4. angular distributions of sputtered impurities (in theta and phi)

GITR can then generate its particle source by sampling particles from those EADs. A more detailed mathematical description of the variables can be found in the attached documents. 

[gitr_variables.pdf](https://github.com/lcpp-org/RustBCA/files/5502297/gitr_variables.pdf)
[gitr_particle_source_eqns.pdf](https://github.com/lcpp-org/RustBCA/files/5502298/gitr_particle_source_eqns.pdf)

**Comment by dcurreli** [comment]
@hayes2419 Few comments:

1. let's agree also on physical units of each quantity 
2. For the two angles theta and phi in your figure (below), we need to define their reference axis (w.r.t. B-field?)
3. Distributions vs. Particle lists

<img width="784" alt="Screen Shot 2020-11-06 at 12 06 59 PM" src="https://user-images.githubusercontent.com/15794365/98399788-94abcd80-2028-11eb-80fc-9ed06929dc9d.png">

**Comment by hayes2419** [comment]
@dcurreli Apologies for later response:
1. Confirming units: energy (eV), fluxes (#/s*m^2), we don't have an angular unit preference between radians and degrees
2. I would think that defining phi wrt the surface normal (rather than the B field) would make it easier to sample particles. Can we use a projection of the B-field where the "forward" direction aligns with the x-axis?
3. We explicitly asked for distributions before, and we don't see a major advantage to using particle lists instead. Because memory-wise, I think it makes more sense to use distributions and then sample particles as we discussed. Tim: "I can envision GITR simulations where we want to focus on a particular area, or 'all areas'. This would result in us needing different lists of particles. Having some control over that and the number of particles in a list, etc is useful I think." Thus, a distribution to me, seems to clearly be the way to go.

**Comment by drobnyjt** [comment]
On the `distributions` branch, I've put together a rough first draft of distribution output for RustBCA. Key points:

- input and output for RustBCA have been abstracted away to a handful of function calls to `input.rs` and `output.rs`
- you can activate the distribution output by using the flag `--features distributions` when building
- for now, I'm directly serializing the EADs to a toml - I've attached an example:[2000.0eV_0.0001deg_He_TiO2_Al_Sidistributions.toml.txt](https://github.com/lcpp-org/RustBCA/files/6039999/2000.0eV_0.0001deg_He_TiO2_Al_Sidistributions.toml.txt)
- output of the particle lists can be suppressed by setting `write_buffer_size` to 0 in `[options]` although empty files will still be created/overwritten (looking for workarounds; I might have to add a `no_output_lists ` feature)
- the `layered_geometries.toml` example can be used to test the functionality
- local angles are in degrees and calculated from the direction (ux, uy, uz) w.r.t. the x-axis - i.e., angle = arctan2(sqrt(uy^2 + uz^2), abs(ux)); this is not final, other ideas are welcome; could you elaborate on your point #2 above?

**Comment by drobnyjt** [comment]
Small update - made some changes to this branch:

- added the `no_list_output` feature. Build with `--features distributions,no_list_output` to activate distribution output and suppress particle list output completely (including no more empty .output files!)
- fixed a typo I introduced at some point to the energy binning that was removing some reflected ions from the EAD

**Comment by drobnyjt** [comment]
I forgot to say it explicitly, but if activate, the distributions feature requires the following added to the [options] block of the input file:
```

**Comment by drobnyjt** [comment]
I've updated the old summary output file to track per-species reflection, sputtering and implantation. Example output (from `layered_geometry.toml`):

`2000.0eV_0.0001deg_He_TiO2_Al_Sisummary.output`
```
mass, reflected, sputtered, deposited
4.002602 24526 0 75474
15.999399999999998 0 17820 0
47.867 0 6059 0
26.98 0 0 0
28.08553 0 0 0
```

**Comment by drobnyjt** [comment]
The distributions feature is now on the main branch; I've done enough light testing to be largely satisfied with it.
