### ISSUE TITLE
[question] Implementing New Lennard-Jones Interactions 

### ISSUE THREAD

**Issue by jackstahl** [lcpp-org/RustBCA#70]
Currently RustBCA has implemented Lennard-Jones potentials with 12-6 and 6.5-6 exponentials. When adding a new potential within interactions.rs, most functions are fairly straightforward, except for the `doca_lennard_jones` function. Is the generalized form below the correct way to add this function?

`4*ε*( (σ/r).powf(m) - (σ/r).powf(n) )`
`(r/σ).powf(m) - 4*ε/relative_energy*( 1-(r/σ).powf(m-n) ) - (p/σ).powf(2)*(r/σ).powf(m-2)`

Thanks for your help!

**Comment by jackstahl** [comment]
I see that there's a whole wiki section answering this exact question! I think that I've figured the issue out.

**Comment by drobnyjt** [comment]
Ok, great! Apologies for not answering immediately, I was out of town all yesterday and have just now started catching up. Feel free to ask any other questions you have!

**Comment by jackstahl** [comment]
Hi, following up on this old question, but would you be able to clarify how to determine the monomial-form polynomial coefficients, and how to add them into the `polynomial_coefficients` function?  Would you also be able to go over how to determine if the  `inverse_transform` function should be `x`, `x*x`, or something else? Finally, can you explain why in `scaling_function`, `n=6` for LJ 6.5-6, but `n=11` for LJ-12-6?

Thanks so much for your help with this barrage of questions!

**Comment by drobnyjt** [comment]
Sure! So what you have to do is completely multiply out the interaction, so you get the interaction in the form:
c[0]*x^n + c[2]*x^(n-1) + ... c[n-1]*x + c[n]
Then, the coefficients c go into polynomial coefficients.

Inverse transform is a function f(x) such that it brings the inverse interaction polynomial up to integer powers - so for the 12-6 potential, f(x) = x because 12 and 6 are both integers, but for the 6.5-6 potential you have to transform x -> x^2 to get a function with all integer powers of x. That sets you up with an order 13 polynomial (hence n+1=14 coefficients in polynomial coefficients). I believe the only place it is used is to _undo_ the transformation from 6.5 to 13 order implicit in polynomial_coefficients when the actual distance of closest approach is needed in the collision algorithm.

Scaling functions are basically educated guesses - a good guess for n is 1 less than the order of the original polynomial. Fiddling with it a bit, I simply found 6 to be a good value.

Hopefully that's clear enough to answer your questions - let me know if anything needs additional clarification.

**Comment by drobnyjt** [comment]
@jackstahl I'll close this issue again since it's been a while - feel free to reach back out if you have any more questions!
